version: '3'

services:
  app:
    container_name: 'users-app'
    image: myapp
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - bbbbb

  bbbbb:
    image: postgres
    container_name: 'postgres-db'
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-pass
      - POSTGRES_DB=users
    ports:
      - "5432:5432"

