version: '3'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'postgres-db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=users'

  app:
    build: ./
    container_name: 'users-app'
    ports:
    - 8080:8080
