apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
#  namespace: pashkov-dev
  labels:
    app.kubernates.io/name: db
    app.kubernates.io/component: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernates.io/name: db
      app.kubernates.io/component: db
  template:
    metadata:
      labels:
        app.kubernates.io/name: db
        app.kubernates.io/component: db
    spec:
      containers:
        - name: mydb
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: test-user
            - name: POSTGRES_PASSWORD
              value: test-pass